"""Regenerate context/assets/ mirrors from live sources.

  python -m scripts.mirror_assets

Writes:
  context/assets/mcp-instructions.md  ← build_instructions()
  context/assets/orient.md            ← @orient on claude_code cell
"""
import json
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent  # flexsearch/
ASSETS = ROOT / "context" / "assets"


def mirror_instructions():
    from flex.mcp_server import build_instructions
    text = build_instructions()
    out = ASSETS / "mcp-instructions.md"
    out.write_text(text + "\n")
    print(f"  {out.relative_to(ROOT)}  ({len(text)} chars)")


def mirror_orient():
    from flex.registry import resolve_cell
    from flex.core import open_cell
    from flex.retrieve.presets import PresetLoader

    path = resolve_cell("claude_code")
    if not path:
        print("  orient: claude_code cell not found, skipping", file=sys.stderr)
        return

    db = open_cell(path)
    loader = PresetLoader(db)
    result = loader.execute(db, "orient", {})

    out = ASSETS / "orient.md"
    data = result  # already a list of dicts from multi-query preset

    lines = [
        "# @orient — claude_code cell",
        "",
        "Auto-generated by `scripts/mirror_assets.py`. Do not edit.",
        "",
    ]

    formatters = {
        "now": _fmt_single,
        "about": _fmt_single,
        "shape": _fmt_shape,
        "query_surface": _fmt_query_surface,
        "hubs": _fmt_hubs,
        "communities": _fmt_communities,
        "presets": _fmt_presets,
        "coverage": _fmt_coverage,
        "sample": _fmt_sample,
    }

    for block in data:
        name = block.get("query", "?")
        lines.append(f"## {name}")
        lines.append("")
        results = block.get("results", [])
        error = block.get("error")
        if error:
            lines.append(f"**error:** {error}")
        elif not results:
            lines.append("*(empty)*")
        else:
            fmt = formatters.get(name, _fmt_table)
            lines.extend(fmt(results))
        lines.append("")

    text = "\n".join(lines)
    out.write_text(text)
    db.close()
    print(f"  {out.relative_to(ROOT)}  ({len(data)} blocks)")


def main():
    ASSETS.mkdir(parents=True, exist_ok=True)
    print("Mirroring assets:")
    mirror_instructions()
    mirror_orient()
    print("Done.")


if __name__ == "__main__":
    main()
